filesystem:
  endpoint: 
  bucket: 
aws:
  access_key: 
  secret_access_key: 
  session_token: 
  default_region: 
requests:
  useragent: Web-FOSS-NL-webfocusedscrape/0.1 (https://github.com/SNStatComp/webfocusedscrape)
  timeout_connect: 3 # In seconds 
  timeout_read: 7 # In seconds 
  max_retries: 3
input:
  input_dir: ../input
  input_files:
    urls: urls.txt
    keywords: keywords.txt
  url_max: 100
  url_offset: 0
  input_variables:
output:
  output_dir: ../output
  batchsize: 100
  logs: logs
crawl:
  max_duration: 500
  max_visits: 200
  max_depth: 2
  use_sitemap: True